// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// arithmetic.cpp
external_pointer<RtImage> rt_image_add_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_add_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_add_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_subtract_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_subtract_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_subtract_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_subtract_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_subtract_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_subtract_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_multiply_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_multiply_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_multiply_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_multiply_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_multiply_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_multiply_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_divide_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_divide_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_divide_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_divide_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_divide_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_divide_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_absdiff_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_absdiff_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_absdiff_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_absdiff_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_absdiff_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_absdiff_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_weighted(external_pointer<RtImage> img1, double alpha, external_pointer<RtImage> img2, double beta, double gamma_val);
extern "C" SEXP _Retina_rt_image_add_weighted(SEXP img1, SEXP alpha, SEXP img2, SEXP beta, SEXP gamma_val) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_weighted(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<double>>(beta), cpp11::as_cpp<cpp11::decay_t<double>>(gamma_val)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_and_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_bitwise_and_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_and_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_and_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_bitwise_and_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_and_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_or_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_bitwise_or_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_or_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_or_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_bitwise_or_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_or_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_xor_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_bitwise_xor_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_xor_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_xor_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_bitwise_xor_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_xor_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_not(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_bitwise_not(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_not(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// capabilities.cpp
bool rt_has_module(std::string module_name);
extern "C" SEXP _Retina_rt_has_module(SEXP module_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_has_module(cpp11::as_cpp<cpp11::decay_t<std::string>>(module_name)));
  END_CPP11
}
// capabilities.cpp
bool rt_has_cuda();
extern "C" SEXP _Retina_rt_has_cuda() {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_has_cuda());
  END_CPP11
}
// channels.cpp
cpp11::list rt_image_split_channels(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_split_channels(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_split_channels(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// channels.cpp
external_pointer<RtImage> rt_image_merge_channels(cpp11::list channel_ptrs, std::string colorspace);
extern "C" SEXP _Retina_rt_image_merge_channels(SEXP channel_ptrs, SEXP colorspace) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_merge_channels(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(channel_ptrs), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace)));
  END_CPP11
}
// colorspace.cpp
external_pointer<RtImage> rt_image_convert_color(external_pointer<RtImage> img, std::string from_cs, std::string to_cs);
extern "C" SEXP _Retina_rt_image_convert_color(SEXP img, SEXP from_cs, SEXP to_cs) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_convert_color(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(from_cs), cpp11::as_cpp<cpp11::decay_t<std::string>>(to_cs)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_randu(int rows, int cols, int nchan, std::string depth, std::string colorspace, double low, double high);
extern "C" SEXP _Retina_rt_randu(SEXP rows, SEXP cols, SEXP nchan, SEXP depth, SEXP colorspace, SEXP low, SEXP high) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_randu(cpp11::as_cpp<cpp11::decay_t<int>>(rows), cpp11::as_cpp<cpp11::decay_t<int>>(cols), cpp11::as_cpp<cpp11::decay_t<int>>(nchan), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<double>>(low), cpp11::as_cpp<cpp11::decay_t<double>>(high)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_randn(int rows, int cols, int nchan, std::string depth, std::string colorspace, double mean, double stddev);
extern "C" SEXP _Retina_rt_randn(SEXP rows, SEXP cols, SEXP nchan, SEXP depth, SEXP colorspace, SEXP mean, SEXP stddev) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_randn(cpp11::as_cpp<cpp11::decay_t<int>>(rows), cpp11::as_cpp<cpp11::decay_t<int>>(cols), cpp11::as_cpp<cpp11::decay_t<int>>(nchan), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<double>>(mean), cpp11::as_cpp<cpp11::decay_t<double>>(stddev)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_border(external_pointer<RtImage> img, int top, int bottom, int left, int right, std::string border_type, doubles value);
extern "C" SEXP _Retina_rt_image_border(SEXP img, SEXP top, SEXP bottom, SEXP left, SEXP right, SEXP border_type, SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_border(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(top), cpp11::as_cpp<cpp11::decay_t<int>>(bottom), cpp11::as_cpp<cpp11::decay_t<int>>(left), cpp11::as_cpp<cpp11::decay_t<int>>(right), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type), cpp11::as_cpp<cpp11::decay_t<doubles>>(value)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_fill(int rows, int cols, int nchan, std::string depth, std::string colorspace, doubles value_vec);
extern "C" SEXP _Retina_rt_fill(SEXP rows, SEXP cols, SEXP nchan, SEXP depth, SEXP colorspace, SEXP value_vec) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_fill(cpp11::as_cpp<cpp11::decay_t<int>>(rows), cpp11::as_cpp<cpp11::decay_t<int>>(cols), cpp11::as_cpp<cpp11::decay_t<int>>(nchan), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<doubles>>(value_vec)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_tile(external_pointer<RtImage> img, int nrow_rep, int ncol_rep);
extern "C" SEXP _Retina_rt_image_tile(SEXP img, SEXP nrow_rep, SEXP ncol_rep) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_tile(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(nrow_rep), cpp11::as_cpp<cpp11::decay_t<int>>(ncol_rep)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_set_to(external_pointer<RtImage> img, doubles value, SEXP mask_ptr);
extern "C" SEXP _Retina_rt_image_set_to(SEXP img, SEXP value, SEXP mask_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_set_to(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(value), cpp11::as_cpp<cpp11::decay_t<SEXP>>(mask_ptr)));
  END_CPP11
}
// display.cpp
integers rt_image_to_native_raster(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_native_raster(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_to_native_raster(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_blur(external_pointer<RtImage> img, int ksize_w, int ksize_h);
extern "C" SEXP _Retina_rt_image_blur(SEXP img, SEXP ksize_w, SEXP ksize_h) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_blur(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_w), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_h)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_gaussian_blur(external_pointer<RtImage> img, int ksize_w, int ksize_h, double sigma_x, double sigma_y);
extern "C" SEXP _Retina_rt_image_gaussian_blur(SEXP img, SEXP ksize_w, SEXP ksize_h, SEXP sigma_x, SEXP sigma_y) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_gaussian_blur(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_w), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_h), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_x), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_y)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_median_blur(external_pointer<RtImage> img, int ksize);
extern "C" SEXP _Retina_rt_image_median_blur(SEXP img, SEXP ksize) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_median_blur(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_bilateral_filter(external_pointer<RtImage> img, int d, double sigma_color, double sigma_space);
extern "C" SEXP _Retina_rt_image_bilateral_filter(SEXP img, SEXP d, SEXP sigma_color, SEXP sigma_space) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bilateral_filter(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(d), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_color), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_space)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_sobel(external_pointer<RtImage> img, int dx, int dy, int ksize, std::string ddepth, double scale, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_sobel(SEXP img, SEXP dx, SEXP dy, SEXP ksize, SEXP ddepth, SEXP scale, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sobel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(dx), cpp11::as_cpp<cpp11::decay_t<int>>(dy), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<std::string>>(ddepth), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_laplacian(external_pointer<RtImage> img, int ksize, std::string ddepth, double scale, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_laplacian(SEXP img, SEXP ksize, SEXP ddepth, SEXP scale, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_laplacian(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<std::string>>(ddepth), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_canny(external_pointer<RtImage> img, double low_threshold, double high_threshold, int aperture_size, bool L2_gradient);
extern "C" SEXP _Retina_rt_image_canny(SEXP img, SEXP low_threshold, SEXP high_threshold, SEXP aperture_size, SEXP L2_gradient) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_canny(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(low_threshold), cpp11::as_cpp<cpp11::decay_t<double>>(high_threshold), cpp11::as_cpp<cpp11::decay_t<int>>(aperture_size), cpp11::as_cpp<cpp11::decay_t<bool>>(L2_gradient)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_resize(external_pointer<RtImage> img, int width, int height, double fx, double fy, std::string interpolation);
extern "C" SEXP _Retina_rt_image_resize(SEXP img, SEXP width, SEXP height, SEXP fx, SEXP fy, SEXP interpolation) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_resize(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(fx), cpp11::as_cpp<cpp11::decay_t<double>>(fy), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_rotate(external_pointer<RtImage> img, double angle, double cx, double cy, double scale, std::string interpolation, std::string border_type);
extern "C" SEXP _Retina_rt_image_rotate(SEXP img, SEXP angle, SEXP cx, SEXP cy, SEXP scale, SEXP interpolation, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_rotate(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(angle), cpp11::as_cpp<cpp11::decay_t<double>>(cx), cpp11::as_cpp<cpp11::decay_t<double>>(cy), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_flip(external_pointer<RtImage> img, int flip_code);
extern "C" SEXP _Retina_rt_image_flip(SEXP img, SEXP flip_code) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_flip(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(flip_code)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_crop(external_pointer<RtImage> img, int x1, int y1, int x2, int y2);
extern "C" SEXP _Retina_rt_image_crop(SEXP img, SEXP x1, SEXP y1, SEXP x2, SEXP y2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_crop(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x1), cpp11::as_cpp<cpp11::decay_t<int>>(y1), cpp11::as_cpp<cpp11::decay_t<int>>(x2), cpp11::as_cpp<cpp11::decay_t<int>>(y2)));
  END_CPP11
}
// image.cpp
bool rt_build_ok();
extern "C" SEXP _Retina_rt_build_ok() {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_build_ok());
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_read(std::string path);
extern "C" SEXP _Retina_rt_image_read(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_read(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_from_integer_array(integers arr, std::string colorspace, std::string depth);
extern "C" SEXP _Retina_rt_image_from_integer_array(SEXP arr, SEXP colorspace, SEXP depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_from_integer_array(cpp11::as_cpp<cpp11::decay_t<integers>>(arr), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth)));
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_from_double_array(doubles arr, std::string colorspace, std::string depth);
extern "C" SEXP _Retina_rt_image_from_double_array(SEXP arr, SEXP colorspace, SEXP depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_from_double_array(cpp11::as_cpp<cpp11::decay_t<doubles>>(arr), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth)));
  END_CPP11
}
// image.cpp
integers rt_image_to_integer_array(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_integer_array(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_to_integer_array(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
doubles rt_image_to_double_array(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_double_array(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_to_double_array(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
void rt_image_write(external_pointer<RtImage> img, std::string path);
extern "C" SEXP _Retina_rt_image_write(SEXP img, SEXP path) {
  BEGIN_CPP11
    rt_image_write(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(path));
    return R_NilValue;
  END_CPP11
}
// image.cpp
void rt_image_to_gpu(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_gpu(SEXP img) {
  BEGIN_CPP11
    rt_image_to_gpu(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img));
    return R_NilValue;
  END_CPP11
}
// image.cpp
void rt_image_to_cpu(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_cpu(SEXP img) {
  BEGIN_CPP11
    rt_image_to_cpu(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img));
    return R_NilValue;
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_clone(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_clone(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_clone(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_nrow(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_nrow(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_nrow(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_ncol(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_ncol(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_ncol(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_nchan(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_nchan(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_nchan(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_depth(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_depth(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_depth(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
bool rt_image_is_gpu(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_is_gpu(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_is_gpu(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
std::string rt_image_colorspace(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_colorspace(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_colorspace(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
void rt_image_set_colorspace(external_pointer<RtImage> img, std::string cs);
extern "C" SEXP _Retina_rt_image_set_colorspace(SEXP img, SEXP cs) {
  BEGIN_CPP11
    rt_image_set_colorspace(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(cs));
    return R_NilValue;
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_convert_depth(external_pointer<RtImage> img, std::string depth);
extern "C" SEXP _Retina_rt_image_convert_depth(SEXP img, SEXP depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_convert_depth(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth)));
  END_CPP11
}
// morphology.cpp
external_pointer<RtImage> rt_image_morph(external_pointer<RtImage> img, std::string op, std::string shape, int size, int iterations, std::string border_type);
extern "C" SEXP _Retina_rt_image_morph(SEXP img, SEXP op, SEXP shape, SEXP size, SEXP iterations, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_morph(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<std::string>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(size), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// morphology.cpp
external_pointer<RtImage> rt_image_morph_custom(external_pointer<RtImage> img, std::string op, cpp11::integers custom_kernel, int iterations, std::string border_type);
extern "C" SEXP _Retina_rt_image_morph_custom(SEXP img, SEXP op, SEXP custom_kernel, SEXP iterations, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_morph_custom(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(custom_kernel), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// pixel.cpp
doubles rt_image_get_pixel(external_pointer<RtImage> img, int row, int col);
extern "C" SEXP _Retina_rt_image_get_pixel(SEXP img, SEXP row, SEXP col) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_get_pixel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(row), cpp11::as_cpp<cpp11::decay_t<int>>(col)));
  END_CPP11
}
// pixel.cpp
void rt_image_set_pixel(external_pointer<RtImage> img, int row, int col, doubles values);
extern "C" SEXP _Retina_rt_image_set_pixel(SEXP img, SEXP row, SEXP col, SEXP values) {
  BEGIN_CPP11
    rt_image_set_pixel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(row), cpp11::as_cpp<cpp11::decay_t<int>>(col), cpp11::as_cpp<cpp11::decay_t<doubles>>(values));
    return R_NilValue;
  END_CPP11
}
// pixel.cpp
external_pointer<RtImage> rt_image_extract_region(external_pointer<RtImage> img, int row_start, int col_start, int row_end, int col_end);
extern "C" SEXP _Retina_rt_image_extract_region(SEXP img, SEXP row_start, SEXP col_start, SEXP row_end, SEXP col_end) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_extract_region(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(row_start), cpp11::as_cpp<cpp11::decay_t<int>>(col_start), cpp11::as_cpp<cpp11::decay_t<int>>(row_end), cpp11::as_cpp<cpp11::decay_t<int>>(col_end)));
  END_CPP11
}
// pixel.cpp
void rt_image_copy_roi(external_pointer<RtImage> dst, external_pointer<RtImage> src, int row_start, int col_start);
extern "C" SEXP _Retina_rt_image_copy_roi(SEXP dst, SEXP src, SEXP row_start, SEXP col_start) {
  BEGIN_CPP11
    rt_image_copy_roi(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(dst), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(src), cpp11::as_cpp<cpp11::decay_t<int>>(row_start), cpp11::as_cpp<cpp11::decay_t<int>>(col_start));
    return R_NilValue;
  END_CPP11
}
// stats.cpp
doubles rt_image_mean(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_mean(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_mean(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_sd(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_sd(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sd(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_var(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_var(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_var(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_min(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_min(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_min(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_max(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_max(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_max(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_sum(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_sum(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sum(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_median(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_median(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_median(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_quantile(external_pointer<RtImage> img, doubles probs);
extern "C" SEXP _Retina_rt_image_quantile(SEXP img, SEXP probs) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_quantile(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(probs)));
  END_CPP11
}
// transforms.cpp
external_pointer<RtImage> rt_image_warp_affine(external_pointer<RtImage> img, doubles m, int width, int height, std::string interpolation, std::string border_type);
extern "C" SEXP _Retina_rt_image_warp_affine(SEXP img, SEXP m, SEXP width, SEXP height, SEXP interpolation, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_warp_affine(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(m), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// transforms.cpp
external_pointer<RtImage> rt_image_warp_perspective(external_pointer<RtImage> img, doubles m, int width, int height, std::string interpolation, std::string border_type);
extern "C" SEXP _Retina_rt_image_warp_perspective(SEXP img, SEXP m, SEXP width, SEXP height, SEXP interpolation, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_warp_perspective(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(m), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// transforms.cpp
doubles rt_affine_rotate(double angle, double cx, double cy, double scale);
extern "C" SEXP _Retina_rt_affine_rotate(SEXP angle, SEXP cx, SEXP cy, SEXP scale) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_affine_rotate(cpp11::as_cpp<cpp11::decay_t<double>>(angle), cpp11::as_cpp<cpp11::decay_t<double>>(cx), cpp11::as_cpp<cpp11::decay_t<double>>(cy), cpp11::as_cpp<cpp11::decay_t<double>>(scale)));
  END_CPP11
}
// transforms.cpp
doubles rt_affine_from_points(doubles src, doubles dst);
extern "C" SEXP _Retina_rt_affine_from_points(SEXP src, SEXP dst) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_affine_from_points(cpp11::as_cpp<cpp11::decay_t<doubles>>(src), cpp11::as_cpp<cpp11::decay_t<doubles>>(dst)));
  END_CPP11
}
// transforms.cpp
doubles rt_perspective_from_points(doubles src, doubles dst);
extern "C" SEXP _Retina_rt_perspective_from_points(SEXP src, SEXP dst) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_perspective_from_points(cpp11::as_cpp<cpp11::decay_t<doubles>>(src), cpp11::as_cpp<cpp11::decay_t<doubles>>(dst)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_Retina_rt_affine_from_points",       (DL_FUNC) &_Retina_rt_affine_from_points,       2},
    {"_Retina_rt_affine_rotate",            (DL_FUNC) &_Retina_rt_affine_rotate,            4},
    {"_Retina_rt_build_ok",                 (DL_FUNC) &_Retina_rt_build_ok,                 0},
    {"_Retina_rt_fill",                     (DL_FUNC) &_Retina_rt_fill,                     6},
    {"_Retina_rt_has_cuda",                 (DL_FUNC) &_Retina_rt_has_cuda,                 0},
    {"_Retina_rt_has_module",               (DL_FUNC) &_Retina_rt_has_module,               1},
    {"_Retina_rt_image_absdiff_image",      (DL_FUNC) &_Retina_rt_image_absdiff_image,      2},
    {"_Retina_rt_image_absdiff_scalar",     (DL_FUNC) &_Retina_rt_image_absdiff_scalar,     2},
    {"_Retina_rt_image_add_image",          (DL_FUNC) &_Retina_rt_image_add_image,          2},
    {"_Retina_rt_image_add_scalar",         (DL_FUNC) &_Retina_rt_image_add_scalar,         2},
    {"_Retina_rt_image_add_weighted",       (DL_FUNC) &_Retina_rt_image_add_weighted,       5},
    {"_Retina_rt_image_bilateral_filter",   (DL_FUNC) &_Retina_rt_image_bilateral_filter,   4},
    {"_Retina_rt_image_bitwise_and_image",  (DL_FUNC) &_Retina_rt_image_bitwise_and_image,  2},
    {"_Retina_rt_image_bitwise_and_scalar", (DL_FUNC) &_Retina_rt_image_bitwise_and_scalar, 2},
    {"_Retina_rt_image_bitwise_not",        (DL_FUNC) &_Retina_rt_image_bitwise_not,        1},
    {"_Retina_rt_image_bitwise_or_image",   (DL_FUNC) &_Retina_rt_image_bitwise_or_image,   2},
    {"_Retina_rt_image_bitwise_or_scalar",  (DL_FUNC) &_Retina_rt_image_bitwise_or_scalar,  2},
    {"_Retina_rt_image_bitwise_xor_image",  (DL_FUNC) &_Retina_rt_image_bitwise_xor_image,  2},
    {"_Retina_rt_image_bitwise_xor_scalar", (DL_FUNC) &_Retina_rt_image_bitwise_xor_scalar, 2},
    {"_Retina_rt_image_blur",               (DL_FUNC) &_Retina_rt_image_blur,               3},
    {"_Retina_rt_image_border",             (DL_FUNC) &_Retina_rt_image_border,             7},
    {"_Retina_rt_image_canny",              (DL_FUNC) &_Retina_rt_image_canny,              5},
    {"_Retina_rt_image_clone",              (DL_FUNC) &_Retina_rt_image_clone,              1},
    {"_Retina_rt_image_colorspace",         (DL_FUNC) &_Retina_rt_image_colorspace,         1},
    {"_Retina_rt_image_convert_color",      (DL_FUNC) &_Retina_rt_image_convert_color,      3},
    {"_Retina_rt_image_convert_depth",      (DL_FUNC) &_Retina_rt_image_convert_depth,      2},
    {"_Retina_rt_image_copy_roi",           (DL_FUNC) &_Retina_rt_image_copy_roi,           4},
    {"_Retina_rt_image_crop",               (DL_FUNC) &_Retina_rt_image_crop,               5},
    {"_Retina_rt_image_depth",              (DL_FUNC) &_Retina_rt_image_depth,              1},
    {"_Retina_rt_image_divide_image",       (DL_FUNC) &_Retina_rt_image_divide_image,       2},
    {"_Retina_rt_image_divide_scalar",      (DL_FUNC) &_Retina_rt_image_divide_scalar,      2},
    {"_Retina_rt_image_extract_region",     (DL_FUNC) &_Retina_rt_image_extract_region,     5},
    {"_Retina_rt_image_flip",               (DL_FUNC) &_Retina_rt_image_flip,               2},
    {"_Retina_rt_image_from_double_array",  (DL_FUNC) &_Retina_rt_image_from_double_array,  3},
    {"_Retina_rt_image_from_integer_array", (DL_FUNC) &_Retina_rt_image_from_integer_array, 3},
    {"_Retina_rt_image_gaussian_blur",      (DL_FUNC) &_Retina_rt_image_gaussian_blur,      5},
    {"_Retina_rt_image_get_pixel",          (DL_FUNC) &_Retina_rt_image_get_pixel,          3},
    {"_Retina_rt_image_is_gpu",             (DL_FUNC) &_Retina_rt_image_is_gpu,             1},
    {"_Retina_rt_image_laplacian",          (DL_FUNC) &_Retina_rt_image_laplacian,          6},
    {"_Retina_rt_image_max",                (DL_FUNC) &_Retina_rt_image_max,                1},
    {"_Retina_rt_image_mean",               (DL_FUNC) &_Retina_rt_image_mean,               1},
    {"_Retina_rt_image_median",             (DL_FUNC) &_Retina_rt_image_median,             1},
    {"_Retina_rt_image_median_blur",        (DL_FUNC) &_Retina_rt_image_median_blur,        2},
    {"_Retina_rt_image_merge_channels",     (DL_FUNC) &_Retina_rt_image_merge_channels,     2},
    {"_Retina_rt_image_min",                (DL_FUNC) &_Retina_rt_image_min,                1},
    {"_Retina_rt_image_morph",              (DL_FUNC) &_Retina_rt_image_morph,              6},
    {"_Retina_rt_image_morph_custom",       (DL_FUNC) &_Retina_rt_image_morph_custom,       5},
    {"_Retina_rt_image_multiply_image",     (DL_FUNC) &_Retina_rt_image_multiply_image,     2},
    {"_Retina_rt_image_multiply_scalar",    (DL_FUNC) &_Retina_rt_image_multiply_scalar,    2},
    {"_Retina_rt_image_nchan",              (DL_FUNC) &_Retina_rt_image_nchan,              1},
    {"_Retina_rt_image_ncol",               (DL_FUNC) &_Retina_rt_image_ncol,               1},
    {"_Retina_rt_image_nrow",               (DL_FUNC) &_Retina_rt_image_nrow,               1},
    {"_Retina_rt_image_quantile",           (DL_FUNC) &_Retina_rt_image_quantile,           2},
    {"_Retina_rt_image_read",               (DL_FUNC) &_Retina_rt_image_read,               1},
    {"_Retina_rt_image_resize",             (DL_FUNC) &_Retina_rt_image_resize,             6},
    {"_Retina_rt_image_rotate",             (DL_FUNC) &_Retina_rt_image_rotate,             7},
    {"_Retina_rt_image_sd",                 (DL_FUNC) &_Retina_rt_image_sd,                 1},
    {"_Retina_rt_image_set_colorspace",     (DL_FUNC) &_Retina_rt_image_set_colorspace,     2},
    {"_Retina_rt_image_set_pixel",          (DL_FUNC) &_Retina_rt_image_set_pixel,          4},
    {"_Retina_rt_image_set_to",             (DL_FUNC) &_Retina_rt_image_set_to,             3},
    {"_Retina_rt_image_sobel",              (DL_FUNC) &_Retina_rt_image_sobel,              8},
    {"_Retina_rt_image_split_channels",     (DL_FUNC) &_Retina_rt_image_split_channels,     1},
    {"_Retina_rt_image_subtract_image",     (DL_FUNC) &_Retina_rt_image_subtract_image,     2},
    {"_Retina_rt_image_subtract_scalar",    (DL_FUNC) &_Retina_rt_image_subtract_scalar,    2},
    {"_Retina_rt_image_sum",                (DL_FUNC) &_Retina_rt_image_sum,                1},
    {"_Retina_rt_image_tile",               (DL_FUNC) &_Retina_rt_image_tile,               3},
    {"_Retina_rt_image_to_cpu",             (DL_FUNC) &_Retina_rt_image_to_cpu,             1},
    {"_Retina_rt_image_to_double_array",    (DL_FUNC) &_Retina_rt_image_to_double_array,    1},
    {"_Retina_rt_image_to_gpu",             (DL_FUNC) &_Retina_rt_image_to_gpu,             1},
    {"_Retina_rt_image_to_integer_array",   (DL_FUNC) &_Retina_rt_image_to_integer_array,   1},
    {"_Retina_rt_image_to_native_raster",   (DL_FUNC) &_Retina_rt_image_to_native_raster,   1},
    {"_Retina_rt_image_var",                (DL_FUNC) &_Retina_rt_image_var,                1},
    {"_Retina_rt_image_warp_affine",        (DL_FUNC) &_Retina_rt_image_warp_affine,        6},
    {"_Retina_rt_image_warp_perspective",   (DL_FUNC) &_Retina_rt_image_warp_perspective,   6},
    {"_Retina_rt_image_write",              (DL_FUNC) &_Retina_rt_image_write,              2},
    {"_Retina_rt_perspective_from_points",  (DL_FUNC) &_Retina_rt_perspective_from_points,  2},
    {"_Retina_rt_randn",                    (DL_FUNC) &_Retina_rt_randn,                    7},
    {"_Retina_rt_randu",                    (DL_FUNC) &_Retina_rt_randu,                    7},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_Retina(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
