// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// arithmetic.cpp
external_pointer<RtImage> rt_image_add_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_add_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_add_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_subtract_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_subtract_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_subtract_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_subtract_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_subtract_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_subtract_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_multiply_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_multiply_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_multiply_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_multiply_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_multiply_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_multiply_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_divide_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_divide_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_divide_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_divide_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_divide_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_divide_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_absdiff_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_absdiff_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_absdiff_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_absdiff_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_absdiff_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_absdiff_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_weighted(external_pointer<RtImage> img1, double alpha, external_pointer<RtImage> img2, double beta, double gamma_val);
extern "C" SEXP _Retina_rt_image_add_weighted(SEXP img1, SEXP alpha, SEXP img2, SEXP beta, SEXP gamma_val) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_weighted(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<double>>(beta), cpp11::as_cpp<cpp11::decay_t<double>>(gamma_val)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_and_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_bitwise_and_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_and_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_and_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_bitwise_and_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_and_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_or_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_bitwise_or_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_or_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_or_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_bitwise_or_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_or_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_xor_image(external_pointer<RtImage> img1, external_pointer<RtImage> img2);
extern "C" SEXP _Retina_rt_image_bitwise_xor_image(SEXP img1, SEXP img2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_xor_image(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_xor_scalar(external_pointer<RtImage> img, doubles values);
extern "C" SEXP _Retina_rt_image_bitwise_xor_scalar(SEXP img, SEXP values) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_xor_scalar(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_not(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_bitwise_not(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_not(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_add_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_add_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_subtract_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_subtract_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_subtract_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_subtract_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_subtract_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_subtract_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_multiply_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_multiply_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_multiply_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_multiply_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_multiply_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_multiply_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_divide_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_divide_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_divide_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_divide_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_divide_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_divide_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_absdiff_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_absdiff_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_absdiff_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_absdiff_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_absdiff_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_absdiff_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_add_weighted_masked(external_pointer<RtImage> img1, double alpha, external_pointer<RtImage> img2, double beta, double gamma_val, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_add_weighted_masked(SEXP img1, SEXP alpha, SEXP img2, SEXP beta, SEXP gamma_val, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_add_weighted_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<double>>(beta), cpp11::as_cpp<cpp11::decay_t<double>>(gamma_val), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_and_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_and_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_and_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_and_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_and_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_and_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_or_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_or_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_or_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_or_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_or_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_or_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_xor_image_masked(external_pointer<RtImage> img1, external_pointer<RtImage> img2, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_xor_image_masked(SEXP img1, SEXP img2, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_xor_image_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img1), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img2), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_xor_scalar_masked(external_pointer<RtImage> img, doubles values, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_xor_scalar_masked(SEXP img, SEXP values, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_xor_scalar_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// arithmetic.cpp
external_pointer<RtImage> rt_image_bitwise_not_masked(external_pointer<RtImage> img, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_bitwise_not_masked(SEXP img, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bitwise_not_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// capabilities.cpp
bool rt_has_module(std::string module_name);
extern "C" SEXP _Retina_rt_has_module(SEXP module_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_has_module(cpp11::as_cpp<cpp11::decay_t<std::string>>(module_name)));
  END_CPP11
}
// capabilities.cpp
bool rt_has_cuda();
extern "C" SEXP _Retina_rt_has_cuda() {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_has_cuda());
  END_CPP11
}
// channels.cpp
cpp11::list rt_image_split_channels(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_split_channels(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_split_channels(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// channels.cpp
external_pointer<RtImage> rt_image_merge_channels(cpp11::list channel_ptrs, std::string colorspace);
extern "C" SEXP _Retina_rt_image_merge_channels(SEXP channel_ptrs, SEXP colorspace) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_merge_channels(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(channel_ptrs), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace)));
  END_CPP11
}
// channels.cpp
external_pointer<RtImage> rt_extract_channel(external_pointer<RtImage> img, int k);
extern "C" SEXP _Retina_rt_extract_channel(SEXP img, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_extract_channel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// channels.cpp
external_pointer<RtImage> rt_insert_channel(external_pointer<RtImage> ch, external_pointer<RtImage> dst_img, int k);
extern "C" SEXP _Retina_rt_insert_channel(SEXP ch, SEXP dst_img, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_insert_channel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(ch), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(dst_img), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// colorspace.cpp
external_pointer<RtImage> rt_image_convert_color(external_pointer<RtImage> img, std::string from_cs, std::string to_cs);
extern "C" SEXP _Retina_rt_image_convert_color(SEXP img, SEXP from_cs, SEXP to_cs) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_convert_color(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(from_cs), cpp11::as_cpp<cpp11::decay_t<std::string>>(to_cs)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_randu(int rows, int cols, int nchan, std::string depth, std::string colorspace, double low, double high);
extern "C" SEXP _Retina_rt_randu(SEXP rows, SEXP cols, SEXP nchan, SEXP depth, SEXP colorspace, SEXP low, SEXP high) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_randu(cpp11::as_cpp<cpp11::decay_t<int>>(rows), cpp11::as_cpp<cpp11::decay_t<int>>(cols), cpp11::as_cpp<cpp11::decay_t<int>>(nchan), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<double>>(low), cpp11::as_cpp<cpp11::decay_t<double>>(high)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_randn(int rows, int cols, int nchan, std::string depth, std::string colorspace, double mean, double stddev);
extern "C" SEXP _Retina_rt_randn(SEXP rows, SEXP cols, SEXP nchan, SEXP depth, SEXP colorspace, SEXP mean, SEXP stddev) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_randn(cpp11::as_cpp<cpp11::decay_t<int>>(rows), cpp11::as_cpp<cpp11::decay_t<int>>(cols), cpp11::as_cpp<cpp11::decay_t<int>>(nchan), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<double>>(mean), cpp11::as_cpp<cpp11::decay_t<double>>(stddev)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_border(external_pointer<RtImage> img, int top, int bottom, int left, int right, std::string border_type, doubles value);
extern "C" SEXP _Retina_rt_image_border(SEXP img, SEXP top, SEXP bottom, SEXP left, SEXP right, SEXP border_type, SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_border(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(top), cpp11::as_cpp<cpp11::decay_t<int>>(bottom), cpp11::as_cpp<cpp11::decay_t<int>>(left), cpp11::as_cpp<cpp11::decay_t<int>>(right), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type), cpp11::as_cpp<cpp11::decay_t<doubles>>(value)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_fill(int rows, int cols, int nchan, std::string depth, std::string colorspace, doubles value_vec);
extern "C" SEXP _Retina_rt_fill(SEXP rows, SEXP cols, SEXP nchan, SEXP depth, SEXP colorspace, SEXP value_vec) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_fill(cpp11::as_cpp<cpp11::decay_t<int>>(rows), cpp11::as_cpp<cpp11::decay_t<int>>(cols), cpp11::as_cpp<cpp11::decay_t<int>>(nchan), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<doubles>>(value_vec)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_tile(external_pointer<RtImage> img, int nrow_rep, int ncol_rep);
extern "C" SEXP _Retina_rt_image_tile(SEXP img, SEXP nrow_rep, SEXP ncol_rep) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_tile(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(nrow_rep), cpp11::as_cpp<cpp11::decay_t<int>>(ncol_rep)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_set_to(external_pointer<RtImage> img, doubles value);
extern "C" SEXP _Retina_rt_image_set_to(SEXP img, SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_set_to(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(value)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_image_set_to_masked(external_pointer<RtImage> img, doubles value, external_pointer<RtImage> mask);
extern "C" SEXP _Retina_rt_image_set_to_masked(SEXP img, SEXP value, SEXP mask) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_set_to_masked(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(value), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(mask)));
  END_CPP11
}
// construct.cpp
external_pointer<RtImage> rt_concatenate(cpp11::list img_ptrs, std::string axis);
extern "C" SEXP _Retina_rt_concatenate(SEXP img_ptrs, SEXP axis) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_concatenate(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(img_ptrs), cpp11::as_cpp<cpp11::decay_t<std::string>>(axis)));
  END_CPP11
}
// display.cpp
integers rt_image_to_native_raster(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_native_raster(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_to_native_raster(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_line(external_pointer<RtImage> img, int x1, int y1, int x2, int y2, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_line(SEXP img, SEXP x1, SEXP y1, SEXP x2, SEXP y2, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_line(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x1), cpp11::as_cpp<cpp11::decay_t<int>>(y1), cpp11::as_cpp<cpp11::decay_t<int>>(x2), cpp11::as_cpp<cpp11::decay_t<int>>(y2), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_arrow(external_pointer<RtImage> img, int x1, int y1, int x2, int y2, doubles color, int thickness, std::string line_type, double tip_length);
extern "C" SEXP _Retina_rt_draw_arrow(SEXP img, SEXP x1, SEXP y1, SEXP x2, SEXP y2, SEXP color, SEXP thickness, SEXP line_type, SEXP tip_length) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_arrow(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x1), cpp11::as_cpp<cpp11::decay_t<int>>(y1), cpp11::as_cpp<cpp11::decay_t<int>>(x2), cpp11::as_cpp<cpp11::decay_t<int>>(y2), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type), cpp11::as_cpp<cpp11::decay_t<double>>(tip_length)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_rectangle(external_pointer<RtImage> img, int x1, int y1, int x2, int y2, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_rectangle(SEXP img, SEXP x1, SEXP y1, SEXP x2, SEXP y2, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_rectangle(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x1), cpp11::as_cpp<cpp11::decay_t<int>>(y1), cpp11::as_cpp<cpp11::decay_t<int>>(x2), cpp11::as_cpp<cpp11::decay_t<int>>(y2), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_circle(external_pointer<RtImage> img, int x, int y, int radius, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_circle(SEXP img, SEXP x, SEXP y, SEXP radius, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_circle(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(y), cpp11::as_cpp<cpp11::decay_t<int>>(radius), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_ellipse(external_pointer<RtImage> img, int x, int y, int rx, int ry, double angle, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_ellipse(SEXP img, SEXP x, SEXP y, SEXP rx, SEXP ry, SEXP angle, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_ellipse(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(y), cpp11::as_cpp<cpp11::decay_t<int>>(rx), cpp11::as_cpp<cpp11::decay_t<int>>(ry), cpp11::as_cpp<cpp11::decay_t<double>>(angle), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_arc(external_pointer<RtImage> img, int x, int y, int rx, int ry, double angle, double start_angle, double end_angle, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_arc(SEXP img, SEXP x, SEXP y, SEXP rx, SEXP ry, SEXP angle, SEXP start_angle, SEXP end_angle, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_arc(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(y), cpp11::as_cpp<cpp11::decay_t<int>>(rx), cpp11::as_cpp<cpp11::decay_t<int>>(ry), cpp11::as_cpp<cpp11::decay_t<double>>(angle), cpp11::as_cpp<cpp11::decay_t<double>>(start_angle), cpp11::as_cpp<cpp11::decay_t<double>>(end_angle), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_polyline(external_pointer<RtImage> img, integers xs, integers ys, bool closed, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_polyline(SEXP img, SEXP xs, SEXP ys, SEXP closed, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_polyline(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<integers>>(xs), cpp11::as_cpp<cpp11::decay_t<integers>>(ys), cpp11::as_cpp<cpp11::decay_t<bool>>(closed), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_fill_poly(external_pointer<RtImage> img, integers xs, integers ys, doubles color, std::string line_type);
extern "C" SEXP _Retina_rt_fill_poly(SEXP img, SEXP xs, SEXP ys, SEXP color, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_fill_poly(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<integers>>(xs), cpp11::as_cpp<cpp11::decay_t<integers>>(ys), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
external_pointer<RtImage> rt_draw_text(external_pointer<RtImage> img, std::string text, int x, int y, std::string font, double font_size, bool italic, doubles color, int thickness, std::string line_type);
extern "C" SEXP _Retina_rt_draw_text(SEXP img, SEXP text, SEXP x, SEXP y, SEXP font, SEXP font_size, SEXP italic, SEXP color, SEXP thickness, SEXP line_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_draw_text(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(text), cpp11::as_cpp<cpp11::decay_t<int>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(y), cpp11::as_cpp<cpp11::decay_t<std::string>>(font), cpp11::as_cpp<cpp11::decay_t<double>>(font_size), cpp11::as_cpp<cpp11::decay_t<bool>>(italic), cpp11::as_cpp<cpp11::decay_t<doubles>>(color), cpp11::as_cpp<cpp11::decay_t<int>>(thickness), cpp11::as_cpp<cpp11::decay_t<std::string>>(line_type)));
  END_CPP11
}
// draw.cpp
list rt_get_text_size(std::string text, std::string font, double font_size, bool italic, int thickness);
extern "C" SEXP _Retina_rt_get_text_size(SEXP text, SEXP font, SEXP font_size, SEXP italic, SEXP thickness) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_get_text_size(cpp11::as_cpp<cpp11::decay_t<std::string>>(text), cpp11::as_cpp<cpp11::decay_t<std::string>>(font), cpp11::as_cpp<cpp11::decay_t<double>>(font_size), cpp11::as_cpp<cpp11::decay_t<bool>>(italic), cpp11::as_cpp<cpp11::decay_t<int>>(thickness)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_blur(external_pointer<RtImage> img, int ksize_w, int ksize_h);
extern "C" SEXP _Retina_rt_image_blur(SEXP img, SEXP ksize_w, SEXP ksize_h) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_blur(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_w), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_h)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_gaussian_blur(external_pointer<RtImage> img, int ksize_w, int ksize_h, double sigma_x, double sigma_y);
extern "C" SEXP _Retina_rt_image_gaussian_blur(SEXP img, SEXP ksize_w, SEXP ksize_h, SEXP sigma_x, SEXP sigma_y) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_gaussian_blur(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_w), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_h), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_x), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_y)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_median_blur(external_pointer<RtImage> img, int ksize);
extern "C" SEXP _Retina_rt_image_median_blur(SEXP img, SEXP ksize) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_median_blur(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_bilateral_filter(external_pointer<RtImage> img, int d, double sigma_color, double sigma_space);
extern "C" SEXP _Retina_rt_image_bilateral_filter(SEXP img, SEXP d, SEXP sigma_color, SEXP sigma_space) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_bilateral_filter(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(d), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_color), cpp11::as_cpp<cpp11::decay_t<double>>(sigma_space)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_sobel(external_pointer<RtImage> img, int dx, int dy, int ksize, std::string ddepth, double scale, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_sobel(SEXP img, SEXP dx, SEXP dy, SEXP ksize, SEXP ddepth, SEXP scale, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sobel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(dx), cpp11::as_cpp<cpp11::decay_t<int>>(dy), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<std::string>>(ddepth), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_laplacian(external_pointer<RtImage> img, int ksize, std::string ddepth, double scale, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_laplacian(SEXP img, SEXP ksize, SEXP ddepth, SEXP scale, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_laplacian(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<std::string>>(ddepth), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_canny(external_pointer<RtImage> img, double low_threshold, double high_threshold, int aperture_size, bool L2_gradient);
extern "C" SEXP _Retina_rt_image_canny(SEXP img, SEXP low_threshold, SEXP high_threshold, SEXP aperture_size, SEXP L2_gradient) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_canny(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(low_threshold), cpp11::as_cpp<cpp11::decay_t<double>>(high_threshold), cpp11::as_cpp<cpp11::decay_t<int>>(aperture_size), cpp11::as_cpp<cpp11::decay_t<bool>>(L2_gradient)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_scharr(external_pointer<RtImage> img, int dx, int dy, std::string ddepth, double scale, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_scharr(SEXP img, SEXP dx, SEXP dy, SEXP ddepth, SEXP scale, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_scharr(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(dx), cpp11::as_cpp<cpp11::decay_t<int>>(dy), cpp11::as_cpp<cpp11::decay_t<std::string>>(ddepth), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_filter2d(external_pointer<RtImage> img, cpp11::doubles kernel_data, int kernel_nrow, int kernel_ncol, int ddepth, int anchor_x, int anchor_y, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_filter2d(SEXP img, SEXP kernel_data, SEXP kernel_nrow, SEXP kernel_ncol, SEXP ddepth, SEXP anchor_x, SEXP anchor_y, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_filter2d(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(kernel_data), cpp11::as_cpp<cpp11::decay_t<int>>(kernel_nrow), cpp11::as_cpp<cpp11::decay_t<int>>(kernel_ncol), cpp11::as_cpp<cpp11::decay_t<int>>(ddepth), cpp11::as_cpp<cpp11::decay_t<int>>(anchor_x), cpp11::as_cpp<cpp11::decay_t<int>>(anchor_y), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
external_pointer<RtImage> rt_image_sep_filter2d(external_pointer<RtImage> img, cpp11::doubles kernel_x, cpp11::doubles kernel_y, int ddepth, int anchor_x, int anchor_y, double delta, std::string border_type);
extern "C" SEXP _Retina_rt_image_sep_filter2d(SEXP img, SEXP kernel_x, SEXP kernel_y, SEXP ddepth, SEXP anchor_x, SEXP anchor_y, SEXP delta, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sep_filter2d(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(kernel_x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(kernel_y), cpp11::as_cpp<cpp11::decay_t<int>>(ddepth), cpp11::as_cpp<cpp11::decay_t<int>>(anchor_x), cpp11::as_cpp<cpp11::decay_t<int>>(anchor_y), cpp11::as_cpp<cpp11::decay_t<double>>(delta), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// filters.cpp
cpp11::writable::integers rt_get_structuring_element(std::string shape, int width, int height);
extern "C" SEXP _Retina_rt_get_structuring_element(SEXP shape, SEXP width, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_get_structuring_element(cpp11::as_cpp<cpp11::decay_t<std::string>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height)));
  END_CPP11
}
// filters.cpp
cpp11::writable::doubles rt_get_gabor_kernel(int ksize_w, int ksize_h, double sigma, double theta_rad, double lambda, double gamma_val, double psi, int ktype);
extern "C" SEXP _Retina_rt_get_gabor_kernel(SEXP ksize_w, SEXP ksize_h, SEXP sigma, SEXP theta_rad, SEXP lambda, SEXP gamma_val, SEXP psi, SEXP ktype) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_get_gabor_kernel(cpp11::as_cpp<cpp11::decay_t<int>>(ksize_w), cpp11::as_cpp<cpp11::decay_t<int>>(ksize_h), cpp11::as_cpp<cpp11::decay_t<double>>(sigma), cpp11::as_cpp<cpp11::decay_t<double>>(theta_rad), cpp11::as_cpp<cpp11::decay_t<double>>(lambda), cpp11::as_cpp<cpp11::decay_t<double>>(gamma_val), cpp11::as_cpp<cpp11::decay_t<double>>(psi), cpp11::as_cpp<cpp11::decay_t<int>>(ktype)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_resize(external_pointer<RtImage> img, int width, int height, double fx, double fy, std::string interpolation);
extern "C" SEXP _Retina_rt_image_resize(SEXP img, SEXP width, SEXP height, SEXP fx, SEXP fy, SEXP interpolation) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_resize(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(fx), cpp11::as_cpp<cpp11::decay_t<double>>(fy), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_rotate(external_pointer<RtImage> img, double angle, double cx, double cy, double scale, std::string interpolation, std::string border_type);
extern "C" SEXP _Retina_rt_image_rotate(SEXP img, SEXP angle, SEXP cx, SEXP cy, SEXP scale, SEXP interpolation, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_rotate(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(angle), cpp11::as_cpp<cpp11::decay_t<double>>(cx), cpp11::as_cpp<cpp11::decay_t<double>>(cy), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_flip(external_pointer<RtImage> img, int flip_code);
extern "C" SEXP _Retina_rt_image_flip(SEXP img, SEXP flip_code) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_flip(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(flip_code)));
  END_CPP11
}
// geometry.cpp
external_pointer<RtImage> rt_image_crop(external_pointer<RtImage> img, int x1, int y1, int x2, int y2);
extern "C" SEXP _Retina_rt_image_crop(SEXP img, SEXP x1, SEXP y1, SEXP x2, SEXP y2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_crop(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(x1), cpp11::as_cpp<cpp11::decay_t<int>>(y1), cpp11::as_cpp<cpp11::decay_t<int>>(x2), cpp11::as_cpp<cpp11::decay_t<int>>(y2)));
  END_CPP11
}
// histogram.cpp
list rt_hist(external_pointer<RtImage> img, int bins, double range_lo, double range_hi);
extern "C" SEXP _Retina_rt_hist(SEXP img, SEXP bins, SEXP range_lo, SEXP range_hi) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_hist(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(bins), cpp11::as_cpp<cpp11::decay_t<double>>(range_lo), cpp11::as_cpp<cpp11::decay_t<double>>(range_hi)));
  END_CPP11
}
// histogram.cpp
external_pointer<RtImage> rt_hist_eq(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_hist_eq(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_hist_eq(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// histogram.cpp
external_pointer<RtImage> rt_lut(external_pointer<RtImage> img, integers lut_vals, int lut_size, int nchan_lut);
extern "C" SEXP _Retina_rt_lut(SEXP img, SEXP lut_vals, SEXP lut_size, SEXP nchan_lut) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_lut(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<integers>>(lut_vals), cpp11::as_cpp<cpp11::decay_t<int>>(lut_size), cpp11::as_cpp<cpp11::decay_t<int>>(nchan_lut)));
  END_CPP11
}
// histogram.cpp
external_pointer<RtImage> rt_clahe(external_pointer<RtImage> img, double clip_limit, int tile_w, int tile_h);
extern "C" SEXP _Retina_rt_clahe(SEXP img, SEXP clip_limit, SEXP tile_w, SEXP tile_h) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_clahe(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(clip_limit), cpp11::as_cpp<cpp11::decay_t<int>>(tile_w), cpp11::as_cpp<cpp11::decay_t<int>>(tile_h)));
  END_CPP11
}
// histogram.cpp
list rt_minmax_loc(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_minmax_loc(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_minmax_loc(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// histogram.cpp
int rt_count_nonzero(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_count_nonzero(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_count_nonzero(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// histogram.cpp
list rt_find_nonzero(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_find_nonzero(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_find_nonzero(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
bool rt_build_ok();
extern "C" SEXP _Retina_rt_build_ok() {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_build_ok());
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_read(std::string path);
extern "C" SEXP _Retina_rt_image_read(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_read(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_from_integer_array(integers arr, std::string colorspace, std::string depth);
extern "C" SEXP _Retina_rt_image_from_integer_array(SEXP arr, SEXP colorspace, SEXP depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_from_integer_array(cpp11::as_cpp<cpp11::decay_t<integers>>(arr), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth)));
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_from_double_array(doubles arr, std::string colorspace, std::string depth);
extern "C" SEXP _Retina_rt_image_from_double_array(SEXP arr, SEXP colorspace, SEXP depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_from_double_array(cpp11::as_cpp<cpp11::decay_t<doubles>>(arr), cpp11::as_cpp<cpp11::decay_t<std::string>>(colorspace), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth)));
  END_CPP11
}
// image.cpp
integers rt_image_to_integer_array(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_integer_array(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_to_integer_array(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
doubles rt_image_to_double_array(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_double_array(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_to_double_array(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
void rt_image_write(external_pointer<RtImage> img, std::string path);
extern "C" SEXP _Retina_rt_image_write(SEXP img, SEXP path) {
  BEGIN_CPP11
    rt_image_write(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(path));
    return R_NilValue;
  END_CPP11
}
// image.cpp
void rt_image_to_gpu(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_gpu(SEXP img) {
  BEGIN_CPP11
    rt_image_to_gpu(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img));
    return R_NilValue;
  END_CPP11
}
// image.cpp
void rt_image_to_cpu(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_to_cpu(SEXP img) {
  BEGIN_CPP11
    rt_image_to_cpu(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img));
    return R_NilValue;
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_clone(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_clone(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_clone(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_nrow(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_nrow(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_nrow(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_ncol(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_ncol(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_ncol(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_nchan(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_nchan(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_nchan(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
int rt_image_depth(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_depth(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_depth(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
bool rt_image_is_gpu(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_is_gpu(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_is_gpu(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
std::string rt_image_colorspace(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_colorspace(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_colorspace(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// image.cpp
void rt_image_set_colorspace(external_pointer<RtImage> img, std::string cs);
extern "C" SEXP _Retina_rt_image_set_colorspace(SEXP img, SEXP cs) {
  BEGIN_CPP11
    rt_image_set_colorspace(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(cs));
    return R_NilValue;
  END_CPP11
}
// image.cpp
external_pointer<RtImage> rt_image_convert_depth(external_pointer<RtImage> img, std::string depth);
extern "C" SEXP _Retina_rt_image_convert_depth(SEXP img, SEXP depth) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_convert_depth(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(depth)));
  END_CPP11
}
// math.cpp
external_pointer<RtImage> rt_pow(external_pointer<RtImage> img, double power);
extern "C" SEXP _Retina_rt_pow(SEXP img, SEXP power) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_pow(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(power)));
  END_CPP11
}
// math.cpp
external_pointer<RtImage> rt_exp(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_exp(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_exp(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// math.cpp
external_pointer<RtImage> rt_log(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_log(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_log(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// math.cpp
external_pointer<RtImage> rt_sqrt(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_sqrt(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_sqrt(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// morphology.cpp
external_pointer<RtImage> rt_image_morph(external_pointer<RtImage> img, std::string op, std::string shape, int size, int iterations, std::string border_type);
extern "C" SEXP _Retina_rt_image_morph(SEXP img, SEXP op, SEXP shape, SEXP size, SEXP iterations, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_morph(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<std::string>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(size), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// morphology.cpp
external_pointer<RtImage> rt_image_morph_custom(external_pointer<RtImage> img, std::string op, cpp11::integers custom_kernel, int iterations, std::string border_type);
extern "C" SEXP _Retina_rt_image_morph_custom(SEXP img, SEXP op, SEXP custom_kernel, SEXP iterations, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_morph_custom(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(custom_kernel), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// pixel.cpp
doubles rt_image_get_pixel(external_pointer<RtImage> img, int row, int col);
extern "C" SEXP _Retina_rt_image_get_pixel(SEXP img, SEXP row, SEXP col) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_get_pixel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(row), cpp11::as_cpp<cpp11::decay_t<int>>(col)));
  END_CPP11
}
// pixel.cpp
void rt_image_set_pixel(external_pointer<RtImage> img, int row, int col, doubles values);
extern "C" SEXP _Retina_rt_image_set_pixel(SEXP img, SEXP row, SEXP col, SEXP values) {
  BEGIN_CPP11
    rt_image_set_pixel(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(row), cpp11::as_cpp<cpp11::decay_t<int>>(col), cpp11::as_cpp<cpp11::decay_t<doubles>>(values));
    return R_NilValue;
  END_CPP11
}
// pixel.cpp
external_pointer<RtImage> rt_image_extract_region(external_pointer<RtImage> img, int row_start, int col_start, int row_end, int col_end);
extern "C" SEXP _Retina_rt_image_extract_region(SEXP img, SEXP row_start, SEXP col_start, SEXP row_end, SEXP col_end) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_extract_region(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<int>>(row_start), cpp11::as_cpp<cpp11::decay_t<int>>(col_start), cpp11::as_cpp<cpp11::decay_t<int>>(row_end), cpp11::as_cpp<cpp11::decay_t<int>>(col_end)));
  END_CPP11
}
// pixel.cpp
void rt_image_copy_roi(external_pointer<RtImage> dst, external_pointer<RtImage> src, int row_start, int col_start);
extern "C" SEXP _Retina_rt_image_copy_roi(SEXP dst, SEXP src, SEXP row_start, SEXP col_start) {
  BEGIN_CPP11
    rt_image_copy_roi(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(dst), cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(src), cpp11::as_cpp<cpp11::decay_t<int>>(row_start), cpp11::as_cpp<cpp11::decay_t<int>>(col_start));
    return R_NilValue;
  END_CPP11
}
// stats.cpp
doubles rt_image_mean(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_mean(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_mean(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_sd(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_sd(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sd(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_var(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_var(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_var(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_min(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_min(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_min(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_max(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_max(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_max(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_sum(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_sum(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_sum(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_median(external_pointer<RtImage> img);
extern "C" SEXP _Retina_rt_image_median(SEXP img) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_median(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img)));
  END_CPP11
}
// stats.cpp
doubles rt_image_quantile(external_pointer<RtImage> img, doubles probs);
extern "C" SEXP _Retina_rt_image_quantile(SEXP img, SEXP probs) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_quantile(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(probs)));
  END_CPP11
}
// threshold.cpp
double rt_autothreshold_value(external_pointer<RtImage> img, std::string method, int bins);
extern "C" SEXP _Retina_rt_autothreshold_value(SEXP img, SEXP method, SEXP bins) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_autothreshold_value(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<int>>(bins)));
  END_CPP11
}
// threshold.cpp
external_pointer<RtImage> rt_image_threshold(external_pointer<RtImage> img, double thresh, double maxval, int type_int);
extern "C" SEXP _Retina_rt_image_threshold(SEXP img, SEXP thresh, SEXP maxval, SEXP type_int) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_threshold(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<double>>(maxval), cpp11::as_cpp<cpp11::decay_t<int>>(type_int)));
  END_CPP11
}
// threshold.cpp
external_pointer<RtImage> rt_image_adaptive_threshold(external_pointer<RtImage> img, double maxval, int method_int, int type_int, int block_size, double offset);
extern "C" SEXP _Retina_rt_image_adaptive_threshold(SEXP img, SEXP maxval, SEXP method_int, SEXP type_int, SEXP block_size, SEXP offset) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_adaptive_threshold(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<double>>(maxval), cpp11::as_cpp<cpp11::decay_t<int>>(method_int), cpp11::as_cpp<cpp11::decay_t<int>>(type_int), cpp11::as_cpp<cpp11::decay_t<int>>(block_size), cpp11::as_cpp<cpp11::decay_t<double>>(offset)));
  END_CPP11
}
// threshold.cpp
external_pointer<RtImage> rt_image_in_range(external_pointer<RtImage> img, cpp11::doubles lo, cpp11::doubles hi);
extern "C" SEXP _Retina_rt_image_in_range(SEXP img, SEXP lo, SEXP hi) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_in_range(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lo), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(hi)));
  END_CPP11
}
// transforms.cpp
external_pointer<RtImage> rt_image_warp_affine(external_pointer<RtImage> img, doubles m, int width, int height, std::string interpolation, std::string border_type);
extern "C" SEXP _Retina_rt_image_warp_affine(SEXP img, SEXP m, SEXP width, SEXP height, SEXP interpolation, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_warp_affine(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(m), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// transforms.cpp
external_pointer<RtImage> rt_image_warp_perspective(external_pointer<RtImage> img, doubles m, int width, int height, std::string interpolation, std::string border_type);
extern "C" SEXP _Retina_rt_image_warp_perspective(SEXP img, SEXP m, SEXP width, SEXP height, SEXP interpolation, SEXP border_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_image_warp_perspective(cpp11::as_cpp<cpp11::decay_t<external_pointer<RtImage>>>(img), cpp11::as_cpp<cpp11::decay_t<doubles>>(m), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<std::string>>(interpolation), cpp11::as_cpp<cpp11::decay_t<std::string>>(border_type)));
  END_CPP11
}
// transforms.cpp
doubles rt_affine_rotate(double angle, double cx, double cy, double scale);
extern "C" SEXP _Retina_rt_affine_rotate(SEXP angle, SEXP cx, SEXP cy, SEXP scale) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_affine_rotate(cpp11::as_cpp<cpp11::decay_t<double>>(angle), cpp11::as_cpp<cpp11::decay_t<double>>(cx), cpp11::as_cpp<cpp11::decay_t<double>>(cy), cpp11::as_cpp<cpp11::decay_t<double>>(scale)));
  END_CPP11
}
// transforms.cpp
doubles rt_affine_from_points(doubles src, doubles dst);
extern "C" SEXP _Retina_rt_affine_from_points(SEXP src, SEXP dst) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_affine_from_points(cpp11::as_cpp<cpp11::decay_t<doubles>>(src), cpp11::as_cpp<cpp11::decay_t<doubles>>(dst)));
  END_CPP11
}
// transforms.cpp
doubles rt_perspective_from_points(doubles src, doubles dst);
extern "C" SEXP _Retina_rt_perspective_from_points(SEXP src, SEXP dst) {
  BEGIN_CPP11
    return cpp11::as_sexp(rt_perspective_from_points(cpp11::as_cpp<cpp11::decay_t<doubles>>(src), cpp11::as_cpp<cpp11::decay_t<doubles>>(dst)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_Retina_rt_affine_from_points",              (DL_FUNC) &_Retina_rt_affine_from_points,               2},
    {"_Retina_rt_affine_rotate",                   (DL_FUNC) &_Retina_rt_affine_rotate,                    4},
    {"_Retina_rt_autothreshold_value",             (DL_FUNC) &_Retina_rt_autothreshold_value,              3},
    {"_Retina_rt_build_ok",                        (DL_FUNC) &_Retina_rt_build_ok,                         0},
    {"_Retina_rt_clahe",                           (DL_FUNC) &_Retina_rt_clahe,                            4},
    {"_Retina_rt_concatenate",                     (DL_FUNC) &_Retina_rt_concatenate,                      2},
    {"_Retina_rt_count_nonzero",                   (DL_FUNC) &_Retina_rt_count_nonzero,                    1},
    {"_Retina_rt_draw_arc",                        (DL_FUNC) &_Retina_rt_draw_arc,                        11},
    {"_Retina_rt_draw_arrow",                      (DL_FUNC) &_Retina_rt_draw_arrow,                       9},
    {"_Retina_rt_draw_circle",                     (DL_FUNC) &_Retina_rt_draw_circle,                      7},
    {"_Retina_rt_draw_ellipse",                    (DL_FUNC) &_Retina_rt_draw_ellipse,                     9},
    {"_Retina_rt_draw_line",                       (DL_FUNC) &_Retina_rt_draw_line,                        8},
    {"_Retina_rt_draw_polyline",                   (DL_FUNC) &_Retina_rt_draw_polyline,                    7},
    {"_Retina_rt_draw_rectangle",                  (DL_FUNC) &_Retina_rt_draw_rectangle,                   8},
    {"_Retina_rt_draw_text",                       (DL_FUNC) &_Retina_rt_draw_text,                       10},
    {"_Retina_rt_exp",                             (DL_FUNC) &_Retina_rt_exp,                              1},
    {"_Retina_rt_extract_channel",                 (DL_FUNC) &_Retina_rt_extract_channel,                  2},
    {"_Retina_rt_fill",                            (DL_FUNC) &_Retina_rt_fill,                             6},
    {"_Retina_rt_fill_poly",                       (DL_FUNC) &_Retina_rt_fill_poly,                        5},
    {"_Retina_rt_find_nonzero",                    (DL_FUNC) &_Retina_rt_find_nonzero,                     1},
    {"_Retina_rt_get_gabor_kernel",                (DL_FUNC) &_Retina_rt_get_gabor_kernel,                 8},
    {"_Retina_rt_get_structuring_element",         (DL_FUNC) &_Retina_rt_get_structuring_element,          3},
    {"_Retina_rt_get_text_size",                   (DL_FUNC) &_Retina_rt_get_text_size,                    5},
    {"_Retina_rt_has_cuda",                        (DL_FUNC) &_Retina_rt_has_cuda,                         0},
    {"_Retina_rt_has_module",                      (DL_FUNC) &_Retina_rt_has_module,                       1},
    {"_Retina_rt_hist",                            (DL_FUNC) &_Retina_rt_hist,                             4},
    {"_Retina_rt_hist_eq",                         (DL_FUNC) &_Retina_rt_hist_eq,                          1},
    {"_Retina_rt_image_absdiff_image",             (DL_FUNC) &_Retina_rt_image_absdiff_image,              2},
    {"_Retina_rt_image_absdiff_image_masked",      (DL_FUNC) &_Retina_rt_image_absdiff_image_masked,       3},
    {"_Retina_rt_image_absdiff_scalar",            (DL_FUNC) &_Retina_rt_image_absdiff_scalar,             2},
    {"_Retina_rt_image_absdiff_scalar_masked",     (DL_FUNC) &_Retina_rt_image_absdiff_scalar_masked,      3},
    {"_Retina_rt_image_adaptive_threshold",        (DL_FUNC) &_Retina_rt_image_adaptive_threshold,         6},
    {"_Retina_rt_image_add_image",                 (DL_FUNC) &_Retina_rt_image_add_image,                  2},
    {"_Retina_rt_image_add_image_masked",          (DL_FUNC) &_Retina_rt_image_add_image_masked,           3},
    {"_Retina_rt_image_add_scalar",                (DL_FUNC) &_Retina_rt_image_add_scalar,                 2},
    {"_Retina_rt_image_add_scalar_masked",         (DL_FUNC) &_Retina_rt_image_add_scalar_masked,          3},
    {"_Retina_rt_image_add_weighted",              (DL_FUNC) &_Retina_rt_image_add_weighted,               5},
    {"_Retina_rt_image_add_weighted_masked",       (DL_FUNC) &_Retina_rt_image_add_weighted_masked,        6},
    {"_Retina_rt_image_bilateral_filter",          (DL_FUNC) &_Retina_rt_image_bilateral_filter,           4},
    {"_Retina_rt_image_bitwise_and_image",         (DL_FUNC) &_Retina_rt_image_bitwise_and_image,          2},
    {"_Retina_rt_image_bitwise_and_image_masked",  (DL_FUNC) &_Retina_rt_image_bitwise_and_image_masked,   3},
    {"_Retina_rt_image_bitwise_and_scalar",        (DL_FUNC) &_Retina_rt_image_bitwise_and_scalar,         2},
    {"_Retina_rt_image_bitwise_and_scalar_masked", (DL_FUNC) &_Retina_rt_image_bitwise_and_scalar_masked,  3},
    {"_Retina_rt_image_bitwise_not",               (DL_FUNC) &_Retina_rt_image_bitwise_not,                1},
    {"_Retina_rt_image_bitwise_not_masked",        (DL_FUNC) &_Retina_rt_image_bitwise_not_masked,         2},
    {"_Retina_rt_image_bitwise_or_image",          (DL_FUNC) &_Retina_rt_image_bitwise_or_image,           2},
    {"_Retina_rt_image_bitwise_or_image_masked",   (DL_FUNC) &_Retina_rt_image_bitwise_or_image_masked,    3},
    {"_Retina_rt_image_bitwise_or_scalar",         (DL_FUNC) &_Retina_rt_image_bitwise_or_scalar,          2},
    {"_Retina_rt_image_bitwise_or_scalar_masked",  (DL_FUNC) &_Retina_rt_image_bitwise_or_scalar_masked,   3},
    {"_Retina_rt_image_bitwise_xor_image",         (DL_FUNC) &_Retina_rt_image_bitwise_xor_image,          2},
    {"_Retina_rt_image_bitwise_xor_image_masked",  (DL_FUNC) &_Retina_rt_image_bitwise_xor_image_masked,   3},
    {"_Retina_rt_image_bitwise_xor_scalar",        (DL_FUNC) &_Retina_rt_image_bitwise_xor_scalar,         2},
    {"_Retina_rt_image_bitwise_xor_scalar_masked", (DL_FUNC) &_Retina_rt_image_bitwise_xor_scalar_masked,  3},
    {"_Retina_rt_image_blur",                      (DL_FUNC) &_Retina_rt_image_blur,                       3},
    {"_Retina_rt_image_border",                    (DL_FUNC) &_Retina_rt_image_border,                     7},
    {"_Retina_rt_image_canny",                     (DL_FUNC) &_Retina_rt_image_canny,                      5},
    {"_Retina_rt_image_clone",                     (DL_FUNC) &_Retina_rt_image_clone,                      1},
    {"_Retina_rt_image_colorspace",                (DL_FUNC) &_Retina_rt_image_colorspace,                 1},
    {"_Retina_rt_image_convert_color",             (DL_FUNC) &_Retina_rt_image_convert_color,              3},
    {"_Retina_rt_image_convert_depth",             (DL_FUNC) &_Retina_rt_image_convert_depth,              2},
    {"_Retina_rt_image_copy_roi",                  (DL_FUNC) &_Retina_rt_image_copy_roi,                   4},
    {"_Retina_rt_image_crop",                      (DL_FUNC) &_Retina_rt_image_crop,                       5},
    {"_Retina_rt_image_depth",                     (DL_FUNC) &_Retina_rt_image_depth,                      1},
    {"_Retina_rt_image_divide_image",              (DL_FUNC) &_Retina_rt_image_divide_image,               2},
    {"_Retina_rt_image_divide_image_masked",       (DL_FUNC) &_Retina_rt_image_divide_image_masked,        3},
    {"_Retina_rt_image_divide_scalar",             (DL_FUNC) &_Retina_rt_image_divide_scalar,              2},
    {"_Retina_rt_image_divide_scalar_masked",      (DL_FUNC) &_Retina_rt_image_divide_scalar_masked,       3},
    {"_Retina_rt_image_extract_region",            (DL_FUNC) &_Retina_rt_image_extract_region,             5},
    {"_Retina_rt_image_filter2d",                  (DL_FUNC) &_Retina_rt_image_filter2d,                   9},
    {"_Retina_rt_image_flip",                      (DL_FUNC) &_Retina_rt_image_flip,                       2},
    {"_Retina_rt_image_from_double_array",         (DL_FUNC) &_Retina_rt_image_from_double_array,          3},
    {"_Retina_rt_image_from_integer_array",        (DL_FUNC) &_Retina_rt_image_from_integer_array,         3},
    {"_Retina_rt_image_gaussian_blur",             (DL_FUNC) &_Retina_rt_image_gaussian_blur,              5},
    {"_Retina_rt_image_get_pixel",                 (DL_FUNC) &_Retina_rt_image_get_pixel,                  3},
    {"_Retina_rt_image_in_range",                  (DL_FUNC) &_Retina_rt_image_in_range,                   3},
    {"_Retina_rt_image_is_gpu",                    (DL_FUNC) &_Retina_rt_image_is_gpu,                     1},
    {"_Retina_rt_image_laplacian",                 (DL_FUNC) &_Retina_rt_image_laplacian,                  6},
    {"_Retina_rt_image_max",                       (DL_FUNC) &_Retina_rt_image_max,                        1},
    {"_Retina_rt_image_mean",                      (DL_FUNC) &_Retina_rt_image_mean,                       1},
    {"_Retina_rt_image_median",                    (DL_FUNC) &_Retina_rt_image_median,                     1},
    {"_Retina_rt_image_median_blur",               (DL_FUNC) &_Retina_rt_image_median_blur,                2},
    {"_Retina_rt_image_merge_channels",            (DL_FUNC) &_Retina_rt_image_merge_channels,             2},
    {"_Retina_rt_image_min",                       (DL_FUNC) &_Retina_rt_image_min,                        1},
    {"_Retina_rt_image_morph",                     (DL_FUNC) &_Retina_rt_image_morph,                      6},
    {"_Retina_rt_image_morph_custom",              (DL_FUNC) &_Retina_rt_image_morph_custom,               5},
    {"_Retina_rt_image_multiply_image",            (DL_FUNC) &_Retina_rt_image_multiply_image,             2},
    {"_Retina_rt_image_multiply_image_masked",     (DL_FUNC) &_Retina_rt_image_multiply_image_masked,      3},
    {"_Retina_rt_image_multiply_scalar",           (DL_FUNC) &_Retina_rt_image_multiply_scalar,            2},
    {"_Retina_rt_image_multiply_scalar_masked",    (DL_FUNC) &_Retina_rt_image_multiply_scalar_masked,     3},
    {"_Retina_rt_image_nchan",                     (DL_FUNC) &_Retina_rt_image_nchan,                      1},
    {"_Retina_rt_image_ncol",                      (DL_FUNC) &_Retina_rt_image_ncol,                       1},
    {"_Retina_rt_image_nrow",                      (DL_FUNC) &_Retina_rt_image_nrow,                       1},
    {"_Retina_rt_image_quantile",                  (DL_FUNC) &_Retina_rt_image_quantile,                   2},
    {"_Retina_rt_image_read",                      (DL_FUNC) &_Retina_rt_image_read,                       1},
    {"_Retina_rt_image_resize",                    (DL_FUNC) &_Retina_rt_image_resize,                     6},
    {"_Retina_rt_image_rotate",                    (DL_FUNC) &_Retina_rt_image_rotate,                     7},
    {"_Retina_rt_image_scharr",                    (DL_FUNC) &_Retina_rt_image_scharr,                     7},
    {"_Retina_rt_image_sd",                        (DL_FUNC) &_Retina_rt_image_sd,                         1},
    {"_Retina_rt_image_sep_filter2d",              (DL_FUNC) &_Retina_rt_image_sep_filter2d,               8},
    {"_Retina_rt_image_set_colorspace",            (DL_FUNC) &_Retina_rt_image_set_colorspace,             2},
    {"_Retina_rt_image_set_pixel",                 (DL_FUNC) &_Retina_rt_image_set_pixel,                  4},
    {"_Retina_rt_image_set_to",                    (DL_FUNC) &_Retina_rt_image_set_to,                     2},
    {"_Retina_rt_image_set_to_masked",             (DL_FUNC) &_Retina_rt_image_set_to_masked,              3},
    {"_Retina_rt_image_sobel",                     (DL_FUNC) &_Retina_rt_image_sobel,                      8},
    {"_Retina_rt_image_split_channels",            (DL_FUNC) &_Retina_rt_image_split_channels,             1},
    {"_Retina_rt_image_subtract_image",            (DL_FUNC) &_Retina_rt_image_subtract_image,             2},
    {"_Retina_rt_image_subtract_image_masked",     (DL_FUNC) &_Retina_rt_image_subtract_image_masked,      3},
    {"_Retina_rt_image_subtract_scalar",           (DL_FUNC) &_Retina_rt_image_subtract_scalar,            2},
    {"_Retina_rt_image_subtract_scalar_masked",    (DL_FUNC) &_Retina_rt_image_subtract_scalar_masked,     3},
    {"_Retina_rt_image_sum",                       (DL_FUNC) &_Retina_rt_image_sum,                        1},
    {"_Retina_rt_image_threshold",                 (DL_FUNC) &_Retina_rt_image_threshold,                  4},
    {"_Retina_rt_image_tile",                      (DL_FUNC) &_Retina_rt_image_tile,                       3},
    {"_Retina_rt_image_to_cpu",                    (DL_FUNC) &_Retina_rt_image_to_cpu,                     1},
    {"_Retina_rt_image_to_double_array",           (DL_FUNC) &_Retina_rt_image_to_double_array,            1},
    {"_Retina_rt_image_to_gpu",                    (DL_FUNC) &_Retina_rt_image_to_gpu,                     1},
    {"_Retina_rt_image_to_integer_array",          (DL_FUNC) &_Retina_rt_image_to_integer_array,           1},
    {"_Retina_rt_image_to_native_raster",          (DL_FUNC) &_Retina_rt_image_to_native_raster,           1},
    {"_Retina_rt_image_var",                       (DL_FUNC) &_Retina_rt_image_var,                        1},
    {"_Retina_rt_image_warp_affine",               (DL_FUNC) &_Retina_rt_image_warp_affine,                6},
    {"_Retina_rt_image_warp_perspective",          (DL_FUNC) &_Retina_rt_image_warp_perspective,           6},
    {"_Retina_rt_image_write",                     (DL_FUNC) &_Retina_rt_image_write,                      2},
    {"_Retina_rt_insert_channel",                  (DL_FUNC) &_Retina_rt_insert_channel,                   3},
    {"_Retina_rt_log",                             (DL_FUNC) &_Retina_rt_log,                              1},
    {"_Retina_rt_lut",                             (DL_FUNC) &_Retina_rt_lut,                              4},
    {"_Retina_rt_minmax_loc",                      (DL_FUNC) &_Retina_rt_minmax_loc,                       1},
    {"_Retina_rt_perspective_from_points",         (DL_FUNC) &_Retina_rt_perspective_from_points,          2},
    {"_Retina_rt_pow",                             (DL_FUNC) &_Retina_rt_pow,                              2},
    {"_Retina_rt_randn",                           (DL_FUNC) &_Retina_rt_randn,                            7},
    {"_Retina_rt_randu",                           (DL_FUNC) &_Retina_rt_randu,                            7},
    {"_Retina_rt_sqrt",                            (DL_FUNC) &_Retina_rt_sqrt,                             1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_Retina(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
