# Generated by cpp11: do not edit by hand

rt_image_add_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_add_image`, img1, img2)
}

rt_image_add_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_add_scalar`, img, values)
}

rt_image_subtract_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_subtract_image`, img1, img2)
}

rt_image_subtract_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_subtract_scalar`, img, values)
}

rt_image_multiply_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_multiply_image`, img1, img2)
}

rt_image_multiply_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_multiply_scalar`, img, values)
}

rt_image_divide_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_divide_image`, img1, img2)
}

rt_image_divide_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_divide_scalar`, img, values)
}

rt_image_absdiff_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_absdiff_image`, img1, img2)
}

rt_image_absdiff_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_absdiff_scalar`, img, values)
}

rt_image_add_weighted <- function(img1, alpha, img2, beta, gamma_val) {
  .Call(`_Retina_rt_image_add_weighted`, img1, alpha, img2, beta, gamma_val)
}

rt_image_bitwise_and_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_bitwise_and_image`, img1, img2)
}

rt_image_bitwise_and_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_bitwise_and_scalar`, img, values)
}

rt_image_bitwise_or_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_bitwise_or_image`, img1, img2)
}

rt_image_bitwise_or_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_bitwise_or_scalar`, img, values)
}

rt_image_bitwise_xor_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_bitwise_xor_image`, img1, img2)
}

rt_image_bitwise_xor_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_bitwise_xor_scalar`, img, values)
}

rt_image_bitwise_not <- function(img) {
  .Call(`_Retina_rt_image_bitwise_not`, img)
}

rt_has_module <- function(module_name) {
  .Call(`_Retina_rt_has_module`, module_name)
}

rt_has_cuda <- function() {
  .Call(`_Retina_rt_has_cuda`)
}

rt_image_split_channels <- function(img) {
  .Call(`_Retina_rt_image_split_channels`, img)
}

rt_image_merge_channels <- function(channel_ptrs, colorspace) {
  .Call(`_Retina_rt_image_merge_channels`, channel_ptrs, colorspace)
}

rt_image_convert_color <- function(img, from_cs, to_cs) {
  .Call(`_Retina_rt_image_convert_color`, img, from_cs, to_cs)
}

rt_randu <- function(rows, cols, nchan, depth, colorspace, low, high) {
  .Call(`_Retina_rt_randu`, rows, cols, nchan, depth, colorspace, low, high)
}

rt_randn <- function(rows, cols, nchan, depth, colorspace, mean, stddev) {
  .Call(`_Retina_rt_randn`, rows, cols, nchan, depth, colorspace, mean, stddev)
}

rt_image_border <- function(img, top, bottom, left, right, border_type, value) {
  .Call(`_Retina_rt_image_border`, img, top, bottom, left, right, border_type, value)
}

rt_fill <- function(rows, cols, nchan, depth, colorspace, value_vec) {
  .Call(`_Retina_rt_fill`, rows, cols, nchan, depth, colorspace, value_vec)
}

rt_image_tile <- function(img, nrow_rep, ncol_rep) {
  .Call(`_Retina_rt_image_tile`, img, nrow_rep, ncol_rep)
}

rt_image_set_to <- function(img, value, mask_ptr) {
  .Call(`_Retina_rt_image_set_to`, img, value, mask_ptr)
}

rt_concatenate <- function(img_ptrs, axis) {
  .Call(`_Retina_rt_concatenate`, img_ptrs, axis)
}

rt_image_to_native_raster <- function(img) {
  .Call(`_Retina_rt_image_to_native_raster`, img)
}

rt_draw_line <- function(img, x1, y1, x2, y2, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_line`, img, x1, y1, x2, y2, color, thickness, line_type)
}

rt_draw_arrow <- function(img, x1, y1, x2, y2, color, thickness, line_type, tip_length) {
  .Call(`_Retina_rt_draw_arrow`, img, x1, y1, x2, y2, color, thickness, line_type, tip_length)
}

rt_draw_rectangle <- function(img, x1, y1, x2, y2, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_rectangle`, img, x1, y1, x2, y2, color, thickness, line_type)
}

rt_draw_circle <- function(img, x, y, radius, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_circle`, img, x, y, radius, color, thickness, line_type)
}

rt_draw_ellipse <- function(img, x, y, rx, ry, angle, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_ellipse`, img, x, y, rx, ry, angle, color, thickness, line_type)
}

rt_draw_arc <- function(img, x, y, rx, ry, angle, start_angle, end_angle, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_arc`, img, x, y, rx, ry, angle, start_angle, end_angle, color, thickness, line_type)
}

rt_draw_polyline <- function(img, xs, ys, closed, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_polyline`, img, xs, ys, closed, color, thickness, line_type)
}

rt_fill_poly <- function(img, xs, ys, color, line_type) {
  .Call(`_Retina_rt_fill_poly`, img, xs, ys, color, line_type)
}

rt_draw_text <- function(img, text, x, y, font, font_size, italic, color, thickness, line_type) {
  .Call(`_Retina_rt_draw_text`, img, text, x, y, font, font_size, italic, color, thickness, line_type)
}

rt_get_text_size <- function(text, font, font_size, italic, thickness) {
  .Call(`_Retina_rt_get_text_size`, text, font, font_size, italic, thickness)
}

rt_image_blur <- function(img, ksize_w, ksize_h) {
  .Call(`_Retina_rt_image_blur`, img, ksize_w, ksize_h)
}

rt_image_gaussian_blur <- function(img, ksize_w, ksize_h, sigma_x, sigma_y) {
  .Call(`_Retina_rt_image_gaussian_blur`, img, ksize_w, ksize_h, sigma_x, sigma_y)
}

rt_image_median_blur <- function(img, ksize) {
  .Call(`_Retina_rt_image_median_blur`, img, ksize)
}

rt_image_bilateral_filter <- function(img, d, sigma_color, sigma_space) {
  .Call(`_Retina_rt_image_bilateral_filter`, img, d, sigma_color, sigma_space)
}

rt_image_sobel <- function(img, dx, dy, ksize, ddepth, scale, delta, border_type) {
  .Call(`_Retina_rt_image_sobel`, img, dx, dy, ksize, ddepth, scale, delta, border_type)
}

rt_image_laplacian <- function(img, ksize, ddepth, scale, delta, border_type) {
  .Call(`_Retina_rt_image_laplacian`, img, ksize, ddepth, scale, delta, border_type)
}

rt_image_canny <- function(img, low_threshold, high_threshold, aperture_size, L2_gradient) {
  .Call(`_Retina_rt_image_canny`, img, low_threshold, high_threshold, aperture_size, L2_gradient)
}

rt_image_scharr <- function(img, dx, dy, ddepth, scale, delta, border_type) {
  .Call(`_Retina_rt_image_scharr`, img, dx, dy, ddepth, scale, delta, border_type)
}

rt_image_filter2d <- function(img, kernel_data, kernel_nrow, kernel_ncol, ddepth, anchor_x, anchor_y, delta, border_type) {
  .Call(`_Retina_rt_image_filter2d`, img, kernel_data, kernel_nrow, kernel_ncol, ddepth, anchor_x, anchor_y, delta, border_type)
}

rt_image_sep_filter2d <- function(img, kernel_x, kernel_y, ddepth, anchor_x, anchor_y, delta, border_type) {
  .Call(`_Retina_rt_image_sep_filter2d`, img, kernel_x, kernel_y, ddepth, anchor_x, anchor_y, delta, border_type)
}

rt_get_structuring_element <- function(shape, width, height) {
  .Call(`_Retina_rt_get_structuring_element`, shape, width, height)
}

rt_get_gabor_kernel <- function(ksize_w, ksize_h, sigma, theta_rad, lambda, gamma_val, psi, ktype) {
  .Call(`_Retina_rt_get_gabor_kernel`, ksize_w, ksize_h, sigma, theta_rad, lambda, gamma_val, psi, ktype)
}

rt_image_resize <- function(img, width, height, fx, fy, interpolation) {
  .Call(`_Retina_rt_image_resize`, img, width, height, fx, fy, interpolation)
}

rt_image_rotate <- function(img, angle, cx, cy, scale, interpolation, border_type) {
  .Call(`_Retina_rt_image_rotate`, img, angle, cx, cy, scale, interpolation, border_type)
}

rt_image_flip <- function(img, flip_code) {
  .Call(`_Retina_rt_image_flip`, img, flip_code)
}

rt_image_crop <- function(img, x1, y1, x2, y2) {
  .Call(`_Retina_rt_image_crop`, img, x1, y1, x2, y2)
}

rt_hist <- function(img, bins, range_lo, range_hi) {
  .Call(`_Retina_rt_hist`, img, bins, range_lo, range_hi)
}

rt_hist_eq <- function(img) {
  .Call(`_Retina_rt_hist_eq`, img)
}

rt_lut <- function(img, lut_vals) {
  .Call(`_Retina_rt_lut`, img, lut_vals)
}

rt_clahe <- function(img, clip_limit, tile_w, tile_h) {
  .Call(`_Retina_rt_clahe`, img, clip_limit, tile_w, tile_h)
}

rt_minmax_loc <- function(img) {
  .Call(`_Retina_rt_minmax_loc`, img)
}

rt_count_nonzero <- function(img) {
  .Call(`_Retina_rt_count_nonzero`, img)
}

rt_find_nonzero <- function(img) {
  .Call(`_Retina_rt_find_nonzero`, img)
}

rt_build_ok <- function() {
  .Call(`_Retina_rt_build_ok`)
}

rt_image_read <- function(path) {
  .Call(`_Retina_rt_image_read`, path)
}

rt_image_from_integer_array <- function(arr, colorspace, depth) {
  .Call(`_Retina_rt_image_from_integer_array`, arr, colorspace, depth)
}

rt_image_from_double_array <- function(arr, colorspace, depth) {
  .Call(`_Retina_rt_image_from_double_array`, arr, colorspace, depth)
}

rt_image_to_integer_array <- function(img) {
  .Call(`_Retina_rt_image_to_integer_array`, img)
}

rt_image_to_double_array <- function(img) {
  .Call(`_Retina_rt_image_to_double_array`, img)
}

rt_image_write <- function(img, path) {
  invisible(.Call(`_Retina_rt_image_write`, img, path))
}

rt_image_to_gpu <- function(img) {
  invisible(.Call(`_Retina_rt_image_to_gpu`, img))
}

rt_image_to_cpu <- function(img) {
  invisible(.Call(`_Retina_rt_image_to_cpu`, img))
}

rt_image_clone <- function(img) {
  .Call(`_Retina_rt_image_clone`, img)
}

rt_image_nrow <- function(img) {
  .Call(`_Retina_rt_image_nrow`, img)
}

rt_image_ncol <- function(img) {
  .Call(`_Retina_rt_image_ncol`, img)
}

rt_image_nchan <- function(img) {
  .Call(`_Retina_rt_image_nchan`, img)
}

rt_image_depth <- function(img) {
  .Call(`_Retina_rt_image_depth`, img)
}

rt_image_is_gpu <- function(img) {
  .Call(`_Retina_rt_image_is_gpu`, img)
}

rt_image_colorspace <- function(img) {
  .Call(`_Retina_rt_image_colorspace`, img)
}

rt_image_set_colorspace <- function(img, cs) {
  invisible(.Call(`_Retina_rt_image_set_colorspace`, img, cs))
}

rt_image_convert_depth <- function(img, depth) {
  .Call(`_Retina_rt_image_convert_depth`, img, depth)
}

rt_pow <- function(img, power) {
  .Call(`_Retina_rt_pow`, img, power)
}

rt_exp <- function(img) {
  .Call(`_Retina_rt_exp`, img)
}

rt_log <- function(img) {
  .Call(`_Retina_rt_log`, img)
}

rt_sqrt <- function(img) {
  .Call(`_Retina_rt_sqrt`, img)
}

rt_image_morph <- function(img, op, shape, size, iterations, border_type) {
  .Call(`_Retina_rt_image_morph`, img, op, shape, size, iterations, border_type)
}

rt_image_morph_custom <- function(img, op, custom_kernel, iterations, border_type) {
  .Call(`_Retina_rt_image_morph_custom`, img, op, custom_kernel, iterations, border_type)
}

rt_image_get_pixel <- function(img, row, col) {
  .Call(`_Retina_rt_image_get_pixel`, img, row, col)
}

rt_image_set_pixel <- function(img, row, col, values) {
  invisible(.Call(`_Retina_rt_image_set_pixel`, img, row, col, values))
}

rt_image_extract_region <- function(img, row_start, col_start, row_end, col_end) {
  .Call(`_Retina_rt_image_extract_region`, img, row_start, col_start, row_end, col_end)
}

rt_image_copy_roi <- function(dst, src, row_start, col_start) {
  invisible(.Call(`_Retina_rt_image_copy_roi`, dst, src, row_start, col_start))
}

rt_image_mean <- function(img) {
  .Call(`_Retina_rt_image_mean`, img)
}

rt_image_sd <- function(img) {
  .Call(`_Retina_rt_image_sd`, img)
}

rt_image_var <- function(img) {
  .Call(`_Retina_rt_image_var`, img)
}

rt_image_min <- function(img) {
  .Call(`_Retina_rt_image_min`, img)
}

rt_image_max <- function(img) {
  .Call(`_Retina_rt_image_max`, img)
}

rt_image_sum <- function(img) {
  .Call(`_Retina_rt_image_sum`, img)
}

rt_image_median <- function(img) {
  .Call(`_Retina_rt_image_median`, img)
}

rt_image_quantile <- function(img, probs) {
  .Call(`_Retina_rt_image_quantile`, img, probs)
}

rt_autothreshold_value <- function(img, method, bins) {
  .Call(`_Retina_rt_autothreshold_value`, img, method, bins)
}

rt_image_threshold <- function(img, thresh, maxval, type_int) {
  .Call(`_Retina_rt_image_threshold`, img, thresh, maxval, type_int)
}

rt_image_adaptive_threshold <- function(img, maxval, method_int, type_int, block_size, offset) {
  .Call(`_Retina_rt_image_adaptive_threshold`, img, maxval, method_int, type_int, block_size, offset)
}

rt_image_in_range <- function(img, lo, hi) {
  .Call(`_Retina_rt_image_in_range`, img, lo, hi)
}

rt_image_warp_affine <- function(img, m, width, height, interpolation, border_type) {
  .Call(`_Retina_rt_image_warp_affine`, img, m, width, height, interpolation, border_type)
}

rt_image_warp_perspective <- function(img, m, width, height, interpolation, border_type) {
  .Call(`_Retina_rt_image_warp_perspective`, img, m, width, height, interpolation, border_type)
}

rt_affine_rotate <- function(angle, cx, cy, scale) {
  .Call(`_Retina_rt_affine_rotate`, angle, cx, cy, scale)
}

rt_affine_from_points <- function(src, dst) {
  .Call(`_Retina_rt_affine_from_points`, src, dst)
}

rt_perspective_from_points <- function(src, dst) {
  .Call(`_Retina_rt_perspective_from_points`, src, dst)
}
