# Generated by cpp11: do not edit by hand

rt_image_add_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_add_image`, img1, img2)
}

rt_image_add_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_add_scalar`, img, values)
}

rt_image_subtract_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_subtract_image`, img1, img2)
}

rt_image_subtract_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_subtract_scalar`, img, values)
}

rt_image_multiply_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_multiply_image`, img1, img2)
}

rt_image_multiply_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_multiply_scalar`, img, values)
}

rt_image_divide_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_divide_image`, img1, img2)
}

rt_image_divide_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_divide_scalar`, img, values)
}

rt_image_absdiff_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_absdiff_image`, img1, img2)
}

rt_image_absdiff_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_absdiff_scalar`, img, values)
}

rt_image_add_weighted <- function(img1, alpha, img2, beta, gamma_val) {
  .Call(`_Retina_rt_image_add_weighted`, img1, alpha, img2, beta, gamma_val)
}

rt_image_bitwise_and_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_bitwise_and_image`, img1, img2)
}

rt_image_bitwise_and_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_bitwise_and_scalar`, img, values)
}

rt_image_bitwise_or_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_bitwise_or_image`, img1, img2)
}

rt_image_bitwise_or_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_bitwise_or_scalar`, img, values)
}

rt_image_bitwise_xor_image <- function(img1, img2) {
  .Call(`_Retina_rt_image_bitwise_xor_image`, img1, img2)
}

rt_image_bitwise_xor_scalar <- function(img, values) {
  .Call(`_Retina_rt_image_bitwise_xor_scalar`, img, values)
}

rt_image_bitwise_not <- function(img) {
  .Call(`_Retina_rt_image_bitwise_not`, img)
}

rt_has_module <- function(module_name) {
  .Call(`_Retina_rt_has_module`, module_name)
}

rt_has_cuda <- function() {
  .Call(`_Retina_rt_has_cuda`)
}

rt_image_split_channels <- function(img) {
  .Call(`_Retina_rt_image_split_channels`, img)
}

rt_image_merge_channels <- function(channel_ptrs, colorspace) {
  .Call(`_Retina_rt_image_merge_channels`, channel_ptrs, colorspace)
}

rt_image_convert_color <- function(img, from_cs, to_cs) {
  .Call(`_Retina_rt_image_convert_color`, img, from_cs, to_cs)
}

rt_image_to_native_raster <- function(img) {
  .Call(`_Retina_rt_image_to_native_raster`, img)
}

rt_image_blur <- function(img, ksize_w, ksize_h) {
  .Call(`_Retina_rt_image_blur`, img, ksize_w, ksize_h)
}

rt_image_gaussian_blur <- function(img, ksize_w, ksize_h, sigma_x, sigma_y) {
  .Call(`_Retina_rt_image_gaussian_blur`, img, ksize_w, ksize_h, sigma_x, sigma_y)
}

rt_image_median_blur <- function(img, ksize) {
  .Call(`_Retina_rt_image_median_blur`, img, ksize)
}

rt_image_bilateral_filter <- function(img, d, sigma_color, sigma_space) {
  .Call(`_Retina_rt_image_bilateral_filter`, img, d, sigma_color, sigma_space)
}

rt_image_sobel <- function(img, dx, dy, ksize, ddepth, scale, delta, border_type) {
  .Call(`_Retina_rt_image_sobel`, img, dx, dy, ksize, ddepth, scale, delta, border_type)
}

rt_image_laplacian <- function(img, ksize, ddepth, scale, delta, border_type) {
  .Call(`_Retina_rt_image_laplacian`, img, ksize, ddepth, scale, delta, border_type)
}

rt_image_canny <- function(img, low_threshold, high_threshold, aperture_size, L2_gradient) {
  .Call(`_Retina_rt_image_canny`, img, low_threshold, high_threshold, aperture_size, L2_gradient)
}

rt_build_ok <- function() {
  .Call(`_Retina_rt_build_ok`)
}

rt_image_read <- function(path) {
  .Call(`_Retina_rt_image_read`, path)
}

rt_image_from_integer_array <- function(arr, colorspace, depth) {
  .Call(`_Retina_rt_image_from_integer_array`, arr, colorspace, depth)
}

rt_image_from_double_array <- function(arr, colorspace, depth) {
  .Call(`_Retina_rt_image_from_double_array`, arr, colorspace, depth)
}

rt_image_to_integer_array <- function(img) {
  .Call(`_Retina_rt_image_to_integer_array`, img)
}

rt_image_to_double_array <- function(img) {
  .Call(`_Retina_rt_image_to_double_array`, img)
}

rt_image_write <- function(img, path) {
  invisible(.Call(`_Retina_rt_image_write`, img, path))
}

rt_image_to_gpu <- function(img) {
  invisible(.Call(`_Retina_rt_image_to_gpu`, img))
}

rt_image_to_cpu <- function(img) {
  invisible(.Call(`_Retina_rt_image_to_cpu`, img))
}

rt_image_clone <- function(img) {
  .Call(`_Retina_rt_image_clone`, img)
}

rt_image_nrow <- function(img) {
  .Call(`_Retina_rt_image_nrow`, img)
}

rt_image_ncol <- function(img) {
  .Call(`_Retina_rt_image_ncol`, img)
}

rt_image_nchan <- function(img) {
  .Call(`_Retina_rt_image_nchan`, img)
}

rt_image_depth <- function(img) {
  .Call(`_Retina_rt_image_depth`, img)
}

rt_image_is_gpu <- function(img) {
  .Call(`_Retina_rt_image_is_gpu`, img)
}

rt_image_colorspace <- function(img) {
  .Call(`_Retina_rt_image_colorspace`, img)
}

rt_image_set_colorspace <- function(img, cs) {
  invisible(.Call(`_Retina_rt_image_set_colorspace`, img, cs))
}

rt_image_convert_depth <- function(img, depth) {
  .Call(`_Retina_rt_image_convert_depth`, img, depth)
}

rt_image_morph <- function(img, op, shape, size, iterations, border_type) {
  .Call(`_Retina_rt_image_morph`, img, op, shape, size, iterations, border_type)
}

rt_image_morph_custom <- function(img, op, custom_kernel, iterations, border_type) {
  .Call(`_Retina_rt_image_morph_custom`, img, op, custom_kernel, iterations, border_type)
}

rt_image_mean <- function(img) {
  .Call(`_Retina_rt_image_mean`, img)
}

rt_image_sd <- function(img) {
  .Call(`_Retina_rt_image_sd`, img)
}

rt_image_var <- function(img) {
  .Call(`_Retina_rt_image_var`, img)
}

rt_image_min <- function(img) {
  .Call(`_Retina_rt_image_min`, img)
}

rt_image_max <- function(img) {
  .Call(`_Retina_rt_image_max`, img)
}

rt_image_sum <- function(img) {
  .Call(`_Retina_rt_image_sum`, img)
}

rt_image_median <- function(img) {
  .Call(`_Retina_rt_image_median`, img)
}

rt_image_quantile <- function(img, probs) {
  .Call(`_Retina_rt_image_quantile`, img, probs)
}
